# Generated by Django 5.1.2 on 2024-11-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0002_asset_kpi_asset"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_id", models.CharField(max_length=50)),
                ("attribute_id", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
                ("value", models.CharField(max_length=100)),
            ],
        ),
    ]
